# Numpy <hr style="border:2.5px solid #5c3ef2ff\"></hr>

<b>Kyle Michael C. Radan</b>
<br>Computer Engineer

In [1]:
#i imports and packages
import numpy as np

# 1D Array

In [2]:
my_array = [1,2,3]
type (my_array)

list

In [3]:
my_array = np.array([1,2,3])
np.shape(my_array)

(3,)

# 2D Array

In [7]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

In [8]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.shape(my_array)

(2, 3)

In [11]:
trans_array = my_array.T
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
np.shape(trans_array)

(3, 2)

In [13]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [14]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])

# Measure of Central Tendency

In [16]:
resistance = np.array([
    [3, 9.1, 9.3, 9.5, 9.8, 9.8, 10.4, 10.4, 10.5, 10.5, 11], #Jaguar
    [9.1, 9.1, 9.1, 9.2, 9.2, 9.9, 9.9, 10.1, 10.8, 11, 20] #Panther
])
resistance

array([[ 3. ,  9.1,  9.3,  9.5,  9.8,  9.8, 10.4, 10.4, 10.5, 10.5, 11. ],
       [ 9.1,  9.1,  9.1,  9.2,  9.2,  9.9,  9.9, 10.1, 10.8, 11. , 20. ]])

In [17]:
np.mean(resistance, axis = 1)

array([ 9.39090909, 10.67272727])